### ISSUE TITLE
Cannot reach it after installation on ubuntu

### ISSUE THREAD

**Issue by albanx** [atomsd/omnibus-atoms#2]
Hi 
I installed the atom on Ubuntu following the instruction. When I hit localhost I just get the default windfly welcome page.

Am I missing any step?

**Comment by atomsd** [comment]
try: http://localhost/atoms

**Comment by albanx** [comment]
Not found :(

**Comment by atomsd** [comment]
can you post log file /var/log/atoms/atoms-server/current ?

**Comment by albanx** [comment]
Attaching here
[current.txt](https://github.com/atomsd/omnibus-atoms/files/211434/current.txt)

**Comment by atomsd** [comment]
Check out your disk space, log error:
Caused by: java.io.IOException: No space left on device.

After adding additional disk space, run the following:
1) sudo rm -rf /var/opt/atoms/
2) sudo atoms-ctl reconfigure

**Comment by albanx** [comment]
it worked. Thank you. :)

**Comment by atomsd** [comment]
For you consideration, just released a new RESTfull API documentation:
http://atomsd.org/documentation/server/rest-api

**Comment by albanx** [comment]
I was wondering if I can receive push notification using html5 push and notification API?

**Comment by atomsd** [comment]
Sure, have a look at https://aerogear.org/javascript/
This project maintain AeroGear clients compatibility.

**Comment by albanx** [comment]
I was looking at the source files but I could not see a service worker that should handle notifications even when you're not on the  website
